### ISSUE TITLE
Crash on respring (iOS 13.5 unc0ver iPhone 6S+)

### ISSUE THREAD

**Issue by nomakewan** [Traurige/Ve#12]
**Describe the bug:** After a respring, springboard crashes and enters safe mode when Ve is installed. Removing Ve resolves the springboard crash.

**Steps to reproduce the behavior:** Install Ve. Respring or rejailbreak to force the springboard process to restart.

**System information:**
- iOS version: 13.5
- Jailbreak: unc0ver

I have attached a crash log to this post. Thank you!
[ve_crashlog.txt](https://github.com/Traurige/Ve/files/9524658/ve_crashlog.txt)

**Comment by Traurige** [comment]
Is this the first time you installed Vē? Thanks for the crash log

**Comment by nomakewan** [comment]
Yes, I just installed it a few minutes ago to track down a phantom notification sound that's been bothering me for months. ApnHistory failed to log it (and heck, it even fails to log Gmail notifications...) and I saw users on Reddit mentioning they were able to use Ve to successfully hunt them down.

**Comment by Traurige** [comment]
We can surely figure the crash out together, but I won’t be at home for another 6 hours. If you have Discord, would you like to give me your tag so I can add you?

**Comment by nomakewan** [comment]
Sure. I'm about to get some sleep but I should be awake in 6~7 hours. It's NomakeWan 1073.

**Comment by Traurige** [comment]
You’ll have to allow friend requests, so I’m allowed to add you

**Comment by nomakewan** [comment]
Whoops, done.
